---
- name: Install Docker using system packages
  hosts: all
  become: yes
  tasks:
    - name: Install Docker using system packages (Ubuntu)
      tags: docker,ubuntu
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker using system packages (CentOS)
      tags: docker,centos
      dnf:
        name:
          - docker
          - docker-compose
        state: present
      when: ansible_distribution == "CentOS"

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

- name: Deploy and manage Nginx container
  hosts: all
  become: yes
  vars:
    container_name: webserver_prod
    image_name: nginx:latest
    host_port: 8080
  tasks:
    - name: Pull the latest Nginx image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Create and run the Nginx container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "{{ host_port }}:80"

